name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }} # Variablesの参照。 gh variable set USERNAME --body 'octocat' でコマンドライン上からセットできる
    steps:
      - run: echo "${USERNAME}"